@echo off

color a

echo Willkommen beim System Tester by Noah DeV
pause

echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!
echo Loading... Pls Wait!

echo Willkommen! / Welcomme!
pause

start no.txt